#!/bin/bash

# battery/power monitor from xfce4
xfce4-power-manager &

# thunar daemon
thunar --daemon &

# restore the previous background
nitrogen --restore &

# status text
dwmstatus &

# systray
trayer --edge top --align right --widthtype request --transparent true --expand true --alpha 0 --tint 0x222222 &

exec dwm
